export function getShortcutLabels(mac: boolean) {
  return {
    newNote: mac ? '⌥N' : 'Ctrl+Shift+1',
    newFolder: mac ? '⌥F' : 'Ctrl+Shift+2',
    search: mac ? '⌘K' : 'Ctrl+K',
    find: mac ? '⌘F' : 'Ctrl+F',
    save: mac ? '⌘S' : 'Ctrl+S',
    toggleSidebar: mac ? '⌥M' : 'Ctrl+Shift+3',
    undo: mac ? '⌘Z' : 'Ctrl+Z',
    redo: mac ? '⌘⇧Z' : 'Ctrl+Y',
    bold: mac ? '⌘B' : 'Ctrl+B',
    italic: mac ? '⌘I' : 'Ctrl+I',
    underline: mac ? '⌘U' : 'Ctrl+U',
    strikethrough: mac ? '⌘⇧X' : 'Ctrl+Shift+X',
    heading1: mac ? '⌘⌥1' : 'Ctrl+1',
    heading2: mac ? '⌘⌥2' : 'Ctrl+2',
    heading3: mac ? '⌘⌥3' : 'Ctrl+3',
    bodyText: mac ? '⌘⌥0' : 'Ctrl+0',
    bulletList: mac ? '⌘⇧8' : 'Ctrl+Shift+8',
    numberedList: mac ? '⌘⇧7' : 'Ctrl+Shift+7',
    inlineCode: mac ? '⌘E' : 'Ctrl+E',
    codeBlock: mac ? '⌘⇧E' : 'Ctrl+Shift+E',
    link: mac ? '⌘K' : 'Ctrl+K',
    quote: mac ? '⌘⇧.' : 'Ctrl+Shift+.',
    navigate: '↑ ↓ ← →',
    openItem: 'Enter',
    rename: 'F2',
    duplicate: mac ? '⌘D' : 'Ctrl+D',
    newTag: mac ? '⌥T' : 'Ctrl+Shift+4',
    deleteItem: mac ? '⌫' : 'Delete',
    selectAll: mac ? '⌘A' : 'Ctrl+A',
    extendSelection: mac ? '⇧↑/↓' : 'Shift+↑/↓',
    multiSelectModifier: mac ? '⌘' : 'Ctrl',
    rangeSelectModifier: mac ? '⇧' : 'Shift'
  };
}
